import { Component } from '@angular/core';

@Component({
  selector: 'app-web-rules-and-regulations',
  templateUrl: './web-rules-and-regulations.component.html',
  styleUrl: './web-rules-and-regulations.component.scss',
})
export class WebRulesAndRegulationsComponent {
  public tableData: any[] = [
    {
      no: 1,
      data: '2024-02-16',
      event: 'Team1',
      one: 1.5,
      x: 3.0,
      two: 2.5,
      oneX: 1.75,
      twelve: 3.0,
      twoX: 2.0,
      handicap1: -1,
      coefficient1: 1.95,
      handicap2: 1,
      coefficient2: 2.05,
      total: 2.5,
      over: 1.85,
      under: 1.85,
    },
    {
      no: 2,
      data: '2024-02-17',
      event: 'Team1',
      one: 2.0,
      x: 3.5,
      two: 1.8,
      oneX: 2.2,
      twelve: 3.5,
      twoX: 1.95,
      handicap1: -5,
      coefficient1: 1.85,
      handicap2: 5,
      coefficient2: 1.95,
      total: 200,
      over: 1.9,
      under: 1.9,
    },
    {
      no: 3,
      data: '2024-02-17',
      event: 'Team1',
      one: 2.0,
      x: 3.5,
      two: 1.8,
      oneX: 2.2,
      twelve: 3.5,
      twoX: 1.95,
      handicap1: -5,
      coefficient1: 1.85,
      handicap2: 5,
      coefficient2: 1.95,
      total: 200,
      over: 1.9,
      under: 1.9,
    },
    {
      no: 4,
      data: '2024-02-17',
      event: 'Team1',
      one: 2.0,
      x: 3.5,
      two: 1.8,
      oneX: 2.2,
      twelve: 3.5,
      twoX: 1.95,
      handicap1: -5,
      coefficient1: 1.85,
      handicap2: 5,
      coefficient2: 1.95,
      total: 200,
      over: 1.9,
      under: 1.9,
    },
    {
      no: 5,
      data: '2024-02-17',
      event: 'Team1',
      one: 2.0,
      x: 3.5,
      two: 1.8,
      oneX: 2.2,
      twelve: 3.5,
      twoX: 1.95,
      handicap1: -5,
      coefficient1: 1.85,
      handicap2: 5,
      coefficient2: 1.95,
      total: 200,
      over: 1.9,
      under: 1.9,
    },
    {
      no: 6,
      data: '2024-02-17',
      event: 'Team1',
      one: 2.0,
      x: 3.5,
      two: 1.8,
      oneX: 2.2,
      twelve: 3.5,
      twoX: 1.95,
      handicap1: -5,
      coefficient1: 1.85,
      handicap2: 5,
      coefficient2: 1.95,
      total: 200,
      over: 1.9,
      under: 1.9,
    },
  ];

  columns: any[] = [
    { header: 'No', field: 'no' },
    { header: 'Data', field: 'data' },
    { header: 'Event', field: 'event' },
    { header: '1', field: 'one' },
    { header: 'x', field: 'x' },
    { header: '2', field: 'two' },
    { header: '1x', field: 'oneX' },
    { header: '12', field: 'twelve' },
    { header: '2x', field: 'twoX' },
    { header: 'Handicap1', field: 'handicap1' },
    { header: 'Coefficient', field: 'coefficient1' },
    { header: 'Handicap2', field: 'handicap2' },
    { header: 'Coefficient', field: 'coefficient2' },
    { header: 'Total', field: 'total' },
    { header: 'Over', field: 'over' },
    { header: 'Under', field: 'under' },
  ];
}
